Repository openshift/containernetworking-plugins, pull requests merged in 2019-09, with the labels that each got.

#14 Bug 1752008: Adds ENV CGO_ENABLED=0 to disable building with cgo
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#15 Bug 1754638: loopback: don't tear down
  plugins/main/loopback/loopback.go
  plugins/main/loopback/loopback_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#17 Bug 1754154: loopback: don't tear down
  plugins/main/loopback/loopback.go
  plugins/main/loopback/loopback_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
