Repository openshift/containernetworking-plugins, pull requests merged in 2020-10, with the labels that each got.

#34 Bug 1878163: Updating ose-containernetworking-plugins builder & base images to be consistent with ART
  Dockerfile
Labels: bugzilla/severity-high, bugzilla/valid-bug

#37 Bug 1879244: ipvlan - make master config as optional
  plugins/main/ipvlan/README.md
  plugins/main/ipvlan/ipvlan.go
  plugins/main/ipvlan/ipvlan_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#35 Updating ose-containernetworking-plugins builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm
